# Generated by Django 2.2 on 2019-08-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_workinexhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
