# Generated by Django 2.2.4 on 2019-08-20 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20190810_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sale_currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sale currency'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sale_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Sale Date'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, default='Diluted acrylic on canvas', max_length=250, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.CharField(default='Rotem Reshef', max_length=200, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rolled',
            field=models.CharField(blank=True, choices=[('R', 'Rolled'), ('S', 'Stretched')], max_length=1, verbose_name='Rolled/Streched'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1, verbose_name='Size (S/L)'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('A', 'Avaliable'), ('O', 'On Loan'), ('S', 'Sold')], default='D', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
