# Generated by Django 2.2.4 on 2019-08-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20190820_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='depth_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='depth in centimeters'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth_in',
            field=models.FloatField(blank=True, default=0.0, help_text='depth in inches'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sold_by',
            field=models.CharField(blank=True, default='Rotem Reshef', max_length=200, verbose_name='Sold By'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rolled',
            field=models.CharField(blank=True, choices=[('R', 'Rolled'), ('S', 'Stretched'), ('F', 'Framed')], max_length=1, verbose_name='Rolled/Streched/Framed'),
        ),
    ]
