# Generated by Django 2.2.4 on 2019-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20190830_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sale_date',
            field=models.DateField(blank=True, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sold_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sold By'),
        ),
    ]
