# Generated by Django 2.2.4 on 2019-08-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20190831_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sale Date'),
        ),
    ]
