# Generated by Django 2.2.4 on 2019-10-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20190831_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='framed',
            field=models.NullBooleanField(verbose_name='Framed'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='depth in centimeters', verbose_name='Depth cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth_in',
            field=models.FloatField(blank=True, default=0.0, help_text='depth in inches', verbose_name='Depth in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='height in centimeters', verbose_name='Height cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_in',
            field=models.FloatField(blank=True, default=0.0, help_text='height in inches', verbose_name='Height in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rolled',
            field=models.CharField(blank=True, choices=[('R', 'Rolled'), ('S', 'Stretched')], max_length=1, verbose_name='Rolled/Streched'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Scroll')], max_length=1, verbose_name='Size Category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('A', 'Avaliable'), ('O', 'On Loan'), ('S', 'Sold')], default='D', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='width in centimeters', verbose_name='Width cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_in',
            field=models.FloatField(blank=True, default=0.0, help_text='width in inches', verbose_name='Width in'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_1',
            field=models.CharField(max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name="Address cont'd"),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, help_text='US state, optional field', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='Zip code'),
        ),
    ]
