# Generated by Django 2.2.4 on 2019-10-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_auto_20191024_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='framed',
            field=models.BooleanField(blank=True, default=False, help_text='Is the work framed?', verbose_name='Framed'),
        ),
    ]
