# Generated by Django 2.2.4 on 2019-10-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20191024_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(help_text='Current location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Location'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.CharField(default='Rotem Reshef', help_text='Current owner', max_length=200, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(help_text='The series', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Series'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('A', 'Avaliable'), ('O', 'On Loan'), ('S', 'Sold')], default='D', help_text='Current status', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text="The works' title", max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(help_text="Series' name", max_length=200, verbose_name='Name'),
        ),
    ]
