# Generated by Django 2.2.4 on 2019-10-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191025_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='name',
            field=models.CharField(help_text='Exhibition name', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Location name', max_length=250, verbose_name='Name'),
        ),
    ]
