# Generated by Django 2.2.4 on 2019-10-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20191025_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='depth_cm',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Depth cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth_in',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Depth in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='framed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Framed'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_cm',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Height cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_in',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Height in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='rolled',
            field=models.CharField(blank=True, choices=[('R', 'Rolled'), ('S', 'Stretched')], max_length=1, verbose_name='Rolled/Streched'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Series'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='sold_by',
            field=models.CharField(blank=True, help_text="The agent's name", max_length=200, verbose_name='Sold By'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(help_text='Artwork title', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_cm',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Width cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_in',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Width in'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(help_text='Series name', max_length=200, verbose_name='Name'),
        ),
    ]
