# Generated by Django 2.2.4 on 2019-10-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20191025_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='depth_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='D', verbose_name='Depth cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='depth_in',
            field=models.FloatField(blank=True, default=0.0, help_text='D', verbose_name='Depth in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='H', verbose_name='Height cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_in',
            field=models.FloatField(blank=True, default=0.0, help_text='H', verbose_name='Height in'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_cm',
            field=models.FloatField(blank=True, default=0.0, help_text='W', verbose_name='Width cm'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_in',
            field=models.FloatField(blank=True, default=0.0, help_text='W', verbose_name='Width in'),
        ),
    ]
