# Generated by Django 2.2.4 on 2019-11-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20191110_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(help_text='Sample image of the artwork', null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
