# Generated by Django 2.2.4 on 2019-11-16 14:43

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20191110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(help_text='Sample image of the artwork', null=True, upload_to=catalogue.models.Artwork.image_file_directory, verbose_name='Image'),
        ),
    ]
