# Generated by Django 2.2.4 on 2019-11-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_auto_20191116_1808'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workinexhibition',
            constraint=models.UniqueConstraint(fields=('artwork', 'exhibition'), name='artwork in exhibition once'),
        ),
    ]
