# Generated by Django 2.2.4 on 2019-11-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20191116_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Scroll')], help_text='How large is this piece?', max_length=1, verbose_name='Size Category'),
        ),
    ]
