# Generated by Django 2.2.4 on 2019-11-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_auto_20191116_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('P', 'Permanent'), ('C', 'Client'), ('G', 'Gallery')], max_length=1, verbose_name='Category'),
        ),
    ]
