# Generated by Django 2.2.4 on 2020-03-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_auto_20200320_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Sample image of the artwork', null=True, upload_to='artworks/', verbose_name='Image')),
            ],
        ),
    ]
