# Generated by Django 2.2.4 on 2020-03-24 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_artworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Artwork'),
            preserve_default=False,
        ),
    ]
