# Generated by Django 2.2.4 on 2020-03-24 00:59

from django.db import migrations


def fill_artworkimage_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Artwork = apps.get_model('catalogue', 'Artwork')
    ArtworkImage = apps.get_model('catalogue', 'ArtworkImage')
    for artwork in Artwork.objects.all():
        artwork_image = ArtworkImage()
        artwork_image.artwork = artwork
        artwork_image.image = artwork.image
        artwork_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0034_artworkimage_artwork'),
    ]

    operations = [
        migrations.RunPython(fill_artworkimage_data),
    ]
