# Generated by Django 2.2.4 on 2020-03-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_auto_20200324_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Artwork'),
        ),
    ]
