# Generated by Django 2.2.4 on 2020-03-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_auto_20200324_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='Sample image of the artwork', null=True, upload_to='artworks/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(help_text='Sample image of the artwork', upload_to='artworks/', verbose_name='Image'),
        ),
    ]
