# Generated by Django 2.2.4 on 2020-03-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0038_auto_20200324_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('A', 'Avaliable'), ('B', 'Dibs'), ('O', 'On Loan'), ('S', 'Sold')], default='D', help_text='Current status', max_length=1, verbose_name='Status'),
        ),
    ]
