# Generated by Django 2.2.4 on 2020-03-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0039_auto_20200325_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip code'),
        ),
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_currency', models.CharField(blank=True, max_length=10, verbose_name='Sale currency')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of final sale', max_digits=10, null=True, verbose_name='Sale Price')),
                ('discount', models.CharField(blank=True, help_text='In amount or percentage', max_length=25, verbose_name='Discount')),
                ('agent_fee', models.DecimalField(blank=True, decimal_places=2, help_text='amount to the agent', max_digits=10, null=True, verbose_name='Amount to Artist')),
                ('amount_to_artist', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to artist after fees', max_digits=10, null=True, verbose_name='Amount to Artist')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Sale Date')),
                ('agent', models.ForeignKey(help_text="The agent's name", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='catalogue.Location')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Artwork')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='catalogue.Location')),
            ],
        ),
    ]
