# Generated by Django 2.2.4 on 2020-03-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0042_auto_20200326_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledata',
            name='agent',
            field=models.ForeignKey(blank=True, help_text="The agent's name", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='catalogue.Location'),
        ),
    ]
