# Generated by Django 2.2.4 on 2020-03-30 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0043_auto_20200329_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledata',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Artwork'),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='catalogue.Location'),
        ),
    ]
