# Generated by Django 2.2.4 on 2020-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0044_auto_20200330_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.CharField(blank=True, default='Rotem Reshef', help_text='Current owner', max_length=200, verbose_name='Owner'),
        ),
    ]
