# Generated by Django 2.2.4 on 2020-04-06 23:07

from django.db import migrations

def fill_activities(apps, schema_editor):
    """fill SaleData table using data from Artwork"""
    Artwork = apps.get_model('catalogue', 'Artwork')
    Location = apps.get_model('catalogue', 'Location')
    Activity = apps.get_model('catalogue', 'Activity')

    for artwork in Artwork.objects.all():
        is_sale = artwork.location.category == 'C'
        activity_type = 'S' if is_sale else 'M'

        activity = Activity(artwork=artwork, 
                            location=artwork.location,
                            activity_type=activity_type)

        activity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_activity'),
    ]

    operations = [
        migrations.RunPython(fill_activities),
    ]
