# Generated by Django 2.2.4 on 2020-04-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0046_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='activity_type',
        ),
    ]
