# Generated by Django 2.2.4 on 2020-04-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0047_auto_20200429_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='position',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='series',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='catalogue.Artwork'),
        ),
    ]
