# Generated by Django 2.1.7 on 2019-04-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('year', models.IntegerField(help_text='Year of creation', verbose_name='Year')),
                ('width_cm', models.FloatField(blank=True, default=0.0, help_text='width in centimeters')),
                ('height_cm', models.FloatField(blank=True, default=0.0, help_text='height in centimeters')),
                ('width_in', models.FloatField(blank=True, default=0.0, help_text='width in inches')),
                ('height_in', models.FloatField(blank=True, default=0.0, help_text='height in inches')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], max_length=1, verbose_name='size category')),
                ('medium', models.CharField(blank=True, max_length=250)),
                ('price_nis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price in US Dollars')),
                ('rolled', models.CharField(blank=True, choices=[('R', 'Rolled'), ('S', 'Stretched')], max_length=1)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Avaliable'), ('O', 'On Loan'), ('S', 'Sold')], default='D', max_length=1)),
                ('owner', models.CharField(default='Rotem Reshef', max_length=200)),
                ('additional', models.TextField(blank=True, verbose_name='Additional info')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Tel Aviv', max_length=64, verbose_name='city')),
                ('state', models.CharField(blank=True, help_text='US state, optional field', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='43701', max_length=5, verbose_name='zip code')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='exhibition',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Location'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Location'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Series'),
        ),
    ]
