# Generated by Django 2.2 on 2019-07-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20190706_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInExhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Artwork')),
                ('exhibition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Exhibition')),
            ],
        ),
    ]
