# Generated by Django 2.2 on 2019-08-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20190809_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.Location'),
        ),
    ]
